/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import controller.EmpleadoBLL;
import controller.ObraBLL;
import controller.ObraEmpleadosBLL;
import entity.EmpleadoTO;
import entity.Obra;
import entity.ObraEmpleado;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author proxc
 */
public class viewObra extends javax.swing.JFrame {

    int z;
    TableColumn agregarColumn;
    String codigo;

    /**
     * Creates new form Home15
     */
    public viewObra() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        listaEmpleados();
        listaObras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_vista = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        obras = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaLis = new javax.swing.JTable();
        AgregarBT = new javax.swing.JPanel();
        listadeempleados1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLista1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnagregar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtCodigo1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtNombre1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        txtEncargado1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txtLugar1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        txtEmpresa1 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        btn_agregar5 = new javax.swing.JLabel();
        btn_agregar6 = new javax.swing.JLabel();
        btn_agregar7 = new javax.swing.JLabel();
        btn_agregar8 = new javax.swing.JLabel();
        EliminarBT = new javax.swing.JPanel();
        listadeempleados2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblLista2 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        btnBuscar4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        txtCodigo2 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        txtNombre2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        txtEncargado2 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        txtLugar2 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        txtEmpresa2 = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        btn_agregar9 = new javax.swing.JLabel();
        btn_agregar10 = new javax.swing.JLabel();
        btn_agregar11 = new javax.swing.JLabel();
        btn_agregar12 = new javax.swing.JLabel();
        Opciones = new javax.swing.JPanel();
        listadeempleados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnBuscar2 = new javax.swing.JButton();
        btnModificar2 = new javax.swing.JButton();
        btnagregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtCodigo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtEncargado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtLugar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        txtEmpresa = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        btn_agregar1 = new javax.swing.JLabel();
        btn_agregar2 = new javax.swing.JLabel();
        btn_agregar3 = new javax.swing.JLabel();
        btn_agregar4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        main.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(31, 97, 141));
        header.setPreferredSize(new java.awt.Dimension(838, 200));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 116, -1, -1));

        btn_vista.setBackground(new java.awt.Color(84, 153, 199));
        btn_vista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista.setText("Vista");
        btn_vista.setOpaque(true);
        btn_vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vistaMouseClicked(evt);
            }
        });
        header.add(btn_vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 200, 170, 30));

        btn_agregar.setBackground(new java.awt.Color(31, 97, 147));
        btn_agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar.setText("Opciones");
        btn_agregar.setOpaque(true);
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });
        header.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 200, 160, 30));

        jLabel3.setBackground(new java.awt.Color(127, 179, 213));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 32, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Obras");
        header.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 290, 80));

        jLabel17.setText("jLabel17");
        header.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BGAB_icon_211x211.png"))); // NOI18N
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, 160));

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DRYWALL FAMILY");
        header.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        home.setLayout(new java.awt.CardLayout());

        obras.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(26, 82, 118));
        jPanel6.setForeground(new java.awt.Color(255, 204, 204));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Lista de Obras");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 340, 30));

        TablaLis.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        TablaLis.setForeground(new java.awt.Color(51, 51, 51));
        TablaLis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Lugar", "Empresa", "Encargado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaLis.setGridColor(new java.awt.Color(255, 255, 255));
        TablaLis.setRowHeight(20);
        TablaLis.setSelectionBackground(new java.awt.Color(26, 82, 118));
        TablaLis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaLisKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TablaLis);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 680, 240));

        javax.swing.GroupLayout obrasLayout = new javax.swing.GroupLayout(obras);
        obras.setLayout(obrasLayout);
        obrasLayout.setHorizontalGroup(
            obrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(obrasLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 487, Short.MAX_VALUE))
        );
        obrasLayout.setVerticalGroup(
            obrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        home.add(obras, "card3");

        AgregarBT.setBackground(new java.awt.Color(255, 255, 255));

        listadeempleados1.setBackground(new java.awt.Color(26, 82, 118));
        listadeempleados1.setForeground(new java.awt.Color(255, 204, 204));
        listadeempleados1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                listadeempleados1MouseDragged(evt);
            }
        });
        listadeempleados1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadeempleados1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listadeempleados1MousePressed(evt);
            }
        });
        listadeempleados1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLista1.setAutoCreateRowSorter(true);
        tblLista1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblLista1.setForeground(new java.awt.Color(102, 102, 102));
        tblLista1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "DNI", "F / N", "Telefono", "Cargo", "Agregar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLista1.setGridColor(new java.awt.Color(51, 51, 51));
        tblLista1.setSelectionBackground(new java.awt.Color(26, 82, 118));
        tblLista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLista1MousePressed(evt);
            }
        });
        tblLista1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblLista1KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblLista1);

        listadeempleados1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 680, 240));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Lista de Empleados");
        listadeempleados1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 340, 50));

        jPanel7.setBackground(new java.awt.Color(26, 82, 118));
        jPanel7.setForeground(new java.awt.Color(255, 204, 204));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Lista de Empleados");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        listadeempleados1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -90, 699, 450));

        btnagregar1.setBackground(new java.awt.Color(255, 255, 255));
        btnagregar1.setText("Agregar");
        btnagregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregar1MouseClicked(evt);
            }
        });
        btnagregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregar1ActionPerformed(evt);
            }
        });
        listadeempleados1.add(btnagregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel19.setText("Datos de la Obra");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 40));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 320, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Codigo:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 190, 10));

        txtCodigo1.setText("ingrese codigo");
        txtCodigo1.setBorder(null);
        txtCodigo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigo1FocusGained(evt);
            }
        });
        txtCodigo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtCodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Nombre:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, 20));

        txtNombre1.setText("ingrese nombre");
        txtNombre1.setBorder(null);
        txtNombre1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombre1FocusGained(evt);
            }
        });
        txtNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Empresa:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 190, 10));

        txtEncargado1.setText("ingrese encargado");
        txtEncargado1.setBorder(null);
        txtEncargado1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEncargado1FocusGained(evt);
            }
        });
        jPanel2.add(txtEncargado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 190, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Lugar");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 332, 180, 0));

        txtLugar1.setText("ingrese lugar");
        txtLugar1.setBorder(null);
        txtLugar1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLugar1FocusGained(evt);
            }
        });
        jPanel2.add(txtLugar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 190, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Encargado:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 392, 90, 0));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 190, 10));

        txtEmpresa1.setText("ingrese apellido");
        txtEmpresa1.setBorder(null);
        txtEmpresa1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmpresa1FocusGained(evt);
            }
        });
        jPanel2.add(txtEmpresa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 190, -1));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, 10));

        btn_agregar5.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar5.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar5.setText("Modificar");
        btn_agregar5.setOpaque(true);
        btn_agregar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar5MouseClicked(evt);
            }
        });
        jPanel2.add(btn_agregar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 110, 30));

        btn_agregar6.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar6.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar6.setText("Buscar");
        btn_agregar6.setOpaque(true);
        btn_agregar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar6MouseClicked(evt);
            }
        });
        jPanel2.add(btn_agregar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 110, 30));

        btn_agregar7.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar7.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar7.setText("Agregar");
        btn_agregar7.setOpaque(true);
        btn_agregar7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar7MouseClicked(evt);
            }
        });
        jPanel2.add(btn_agregar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 110, 30));

        btn_agregar8.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar8.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar8.setText("Eliminar");
        btn_agregar8.setOpaque(true);
        btn_agregar8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar8MouseClicked(evt);
            }
        });
        jPanel2.add(btn_agregar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 110, 30));

        javax.swing.GroupLayout AgregarBTLayout = new javax.swing.GroupLayout(AgregarBT);
        AgregarBT.setLayout(AgregarBTLayout);
        AgregarBTLayout.setHorizontalGroup(
            AgregarBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarBTLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1505, Short.MAX_VALUE))
            .addGroup(AgregarBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AgregarBTLayout.createSequentialGroup()
                    .addContainerGap(513, Short.MAX_VALUE)
                    .addComponent(listadeempleados1, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(530, Short.MAX_VALUE)))
        );
        AgregarBTLayout.setVerticalGroup(
            AgregarBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(AgregarBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(listadeempleados1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        home.add(AgregarBT, "card3");

        EliminarBT.setBackground(new java.awt.Color(255, 255, 255));

        listadeempleados2.setBackground(new java.awt.Color(26, 82, 118));
        listadeempleados2.setForeground(new java.awt.Color(255, 204, 204));
        listadeempleados2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                listadeempleados2MouseDragged(evt);
            }
        });
        listadeempleados2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadeempleados2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listadeempleados2MousePressed(evt);
            }
        });
        listadeempleados2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLista2.setAutoCreateRowSorter(true);
        tblLista2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblLista2.setForeground(new java.awt.Color(102, 102, 102));
        tblLista2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "DNI", "F / N", "Telefono", "Cargo", "Eliminar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLista2.setGridColor(new java.awt.Color(51, 51, 51));
        tblLista2.setSelectionBackground(new java.awt.Color(26, 82, 118));
        tblLista2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLista2MousePressed(evt);
            }
        });
        tblLista2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblLista2KeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tblLista2);

        listadeempleados2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 680, 240));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Lista de Empleados");
        listadeempleados2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 340, 50));

        jPanel8.setBackground(new java.awt.Color(26, 82, 118));
        jPanel8.setForeground(new java.awt.Color(255, 204, 204));
        jPanel8.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel8MouseDragged(evt);
            }
        });
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel8MousePressed(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Lista de Empleados");
        jPanel8.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        listadeempleados2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -90, 699, 450));

        btnBuscar4.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar4.setText("Eliminar");
        btnBuscar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar4ActionPerformed(evt);
            }
        });
        listadeempleados2.add(btnBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setText("Datos de la Obra");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 40));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 320, 20));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setText("Codigo:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 190, 10));

        txtCodigo2.setText("ingrese codigo");
        txtCodigo2.setBorder(null);
        txtCodigo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigo2FocusGained(evt);
            }
        });
        txtCodigo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo2ActionPerformed(evt);
            }
        });
        jPanel3.add(txtCodigo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel30.setText("Nombre:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        jPanel3.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, 20));

        txtNombre2.setText("ingrese nombre");
        txtNombre2.setBorder(null);
        txtNombre2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombre2FocusGained(evt);
            }
        });
        txtNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre2ActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setText("Empresa:");
        jPanel3.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));
        jPanel3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 190, 10));

        txtEncargado2.setText("ingrese encargado");
        txtEncargado2.setBorder(null);
        txtEncargado2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEncargado2FocusGained(evt);
            }
        });
        jPanel3.add(txtEncargado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 190, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setText("Lugar");
        jPanel3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));
        jPanel3.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 332, 180, 0));

        txtLugar2.setText("ingrese lugar");
        txtLugar2.setBorder(null);
        txtLugar2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLugar2FocusGained(evt);
            }
        });
        jPanel3.add(txtLugar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 190, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setText("Encargado:");
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
        jPanel3.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 392, 90, 0));
        jPanel3.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 190, 10));

        txtEmpresa2.setText("ingrese apellido");
        txtEmpresa2.setBorder(null);
        txtEmpresa2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmpresa2FocusGained(evt);
            }
        });
        jPanel3.add(txtEmpresa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 190, -1));
        jPanel3.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, 10));

        btn_agregar9.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar9.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar9.setText("Modificar");
        btn_agregar9.setOpaque(true);
        btn_agregar9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar9MouseClicked(evt);
            }
        });
        jPanel3.add(btn_agregar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 110, 30));

        btn_agregar10.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar10.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar10.setText("Buscar");
        btn_agregar10.setOpaque(true);
        btn_agregar10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar10MouseClicked(evt);
            }
        });
        jPanel3.add(btn_agregar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 110, 30));

        btn_agregar11.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar11.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar11.setText("Agregar");
        btn_agregar11.setOpaque(true);
        btn_agregar11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar11MouseClicked(evt);
            }
        });
        jPanel3.add(btn_agregar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 110, 30));

        btn_agregar12.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar12.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar12.setText("Eliminar");
        btn_agregar12.setOpaque(true);
        btn_agregar12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar12MouseClicked(evt);
            }
        });
        jPanel3.add(btn_agregar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 110, 30));

        javax.swing.GroupLayout EliminarBTLayout = new javax.swing.GroupLayout(EliminarBT);
        EliminarBT.setLayout(EliminarBTLayout);
        EliminarBTLayout.setHorizontalGroup(
            EliminarBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarBTLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1505, Short.MAX_VALUE))
            .addGroup(EliminarBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EliminarBTLayout.createSequentialGroup()
                    .addContainerGap(513, Short.MAX_VALUE)
                    .addComponent(listadeempleados2, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(530, Short.MAX_VALUE)))
        );
        EliminarBTLayout.setVerticalGroup(
            EliminarBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addGroup(EliminarBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(listadeempleados2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE))
        );

        home.add(EliminarBT, "card3");

        Opciones.setBackground(new java.awt.Color(255, 255, 255));

        listadeempleados.setBackground(new java.awt.Color(26, 82, 118));
        listadeempleados.setForeground(new java.awt.Color(255, 204, 204));
        listadeempleados.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                listadeempleadosMouseDragged(evt);
            }
        });
        listadeempleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadeempleadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                listadeempleadosMousePressed(evt);
            }
        });
        listadeempleados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLista.setAutoCreateRowSorter(true);
        tblLista.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblLista.setForeground(new java.awt.Color(102, 102, 102));
        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "DNI", "F / N", "Telefono", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLista.setGridColor(new java.awt.Color(51, 51, 51));
        tblLista.setSelectionBackground(new java.awt.Color(26, 82, 118));
        tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblListaMousePressed(evt);
            }
        });
        tblLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblListaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblLista);

        listadeempleados.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 680, 240));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Lista de Empleados");
        listadeempleados.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 340, 50));

        jPanel5.setBackground(new java.awt.Color(26, 82, 118));
        jPanel5.setForeground(new java.awt.Color(255, 204, 204));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Lista de Empleados");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        listadeempleados.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -90, 699, 450));

        btnBuscar2.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar2.setText("Eliminar");
        btnBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar2ActionPerformed(evt);
            }
        });
        listadeempleados.add(btnBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, -1));

        btnModificar2.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar2.setText("Modificar");
        btnModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar2ActionPerformed(evt);
            }
        });
        listadeempleados.add(btnModificar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        btnagregar.setBackground(new java.awt.Color(255, 255, 255));
        btnagregar.setText("Agregar");
        btnagregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarMouseClicked(evt);
            }
        });
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        listadeempleados.add(btnagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Datos de la Obra");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, 40));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 320, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Codigo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 190, 10));

        txtCodigo.setBorder(null);
        txtCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodigoFocusGained(evt);
            }
        });
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 190, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Nombre:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 190, 20));

        txtNombre.setText("ingrese nombre");
        txtNombre.setBorder(null);
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 190, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Empresa:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 190, 10));

        txtEncargado.setText("ingrese encargado");
        txtEncargado.setBorder(null);
        txtEncargado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEncargadoFocusGained(evt);
            }
        });
        jPanel1.add(txtEncargado, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 190, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Lugar");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 332, 180, 0));

        txtLugar.setText("ingrese lugar");
        txtLugar.setBorder(null);
        txtLugar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtLugarFocusGained(evt);
            }
        });
        jPanel1.add(txtLugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 190, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Encargado:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 392, 90, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 190, 10));

        txtEmpresa.setText("ingrese empresa");
        txtEmpresa.setBorder(null);
        txtEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmpresaFocusGained(evt);
            }
        });
        jPanel1.add(txtEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 190, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 190, 10));

        btn_agregar1.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar1.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar1.setText("Modificar");
        btn_agregar1.setOpaque(true);
        btn_agregar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar1MouseClicked(evt);
            }
        });
        jPanel1.add(btn_agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 110, 30));

        btn_agregar2.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar2.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar2.setText("Buscar");
        btn_agregar2.setOpaque(true);
        btn_agregar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar2MouseClicked(evt);
            }
        });
        jPanel1.add(btn_agregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 110, 30));

        btn_agregar3.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar3.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar3.setText("Agregar");
        btn_agregar3.setOpaque(true);
        btn_agregar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar3MouseClicked(evt);
            }
        });
        jPanel1.add(btn_agregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 110, 30));

        btn_agregar4.setBackground(new java.awt.Color(84, 153, 199));
        btn_agregar4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar4.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar4.setText("Eliminar");
        btn_agregar4.setOpaque(true);
        btn_agregar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregar4MouseClicked(evt);
            }
        });
        jPanel1.add(btn_agregar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 110, 30));

        javax.swing.GroupLayout OpcionesLayout = new javax.swing.GroupLayout(Opciones);
        Opciones.setLayout(OpcionesLayout);
        OpcionesLayout.setHorizontalGroup(
            OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OpcionesLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listadeempleados, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 525, Short.MAX_VALUE))
        );
        OpcionesLayout.setVerticalGroup(
            OpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .addComponent(listadeempleados, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        home.add(Opciones, "card3");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_headerMouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_vistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vistaMouseClicked
        // TODO add your handling code here:
        listaObras();
        setLblColor(btn_vista);
        resetLblColor(btn_agregar);
        Opciones.setVisible(false);

        obras.setVisible(true);

    }//GEN-LAST:event_btn_vistaMouseClicked

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        setLblColor(btn_agregar);
        resetLblColor(btn_vista);
        Opciones.setVisible(true);
        obras.setVisible(false);
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

    }//GEN-LAST:event_jPanel1MouseDragged

    private void txtLugarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLugarFocusGained
        txtLugar.setText("");
    }//GEN-LAST:event_txtLugarFocusGained

    private void txtEncargadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEncargadoFocusGained
        txtEncargado.setText("");
    }//GEN-LAST:event_txtEncargadoFocusGained

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreFocusGained

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFocusGained

    }//GEN-LAST:event_txtCodigoFocusGained

    private void txtEmpresaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmpresaFocusGained
        txtEmpresa.setText("");
    }//GEN-LAST:event_txtEmpresaFocusGained

    private void tblListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMousePressed
        int filaSeleccionada = this.tblLista.getSelectedRow();//Identificamos que fila ha sido seleccionada

        try {
            this.txtCodigo.setText(tblLista.getValueAt(filaSeleccionada, 0).toString());
            this.txtNombre.setText(tblLista.getValueAt(filaSeleccionada, 1).toString());
            this.txtEncargado.setText(tblLista.getValueAt(filaSeleccionada, 2).toString());
            this.txtLugar.setText(tblLista.getValueAt(filaSeleccionada, 3).toString());
            this.txtEmpresa.setText(tblLista.getValueAt(filaSeleccionada, 4).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tblListaMousePressed

    private void tblListaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListaKeyReleased
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            int filaSeleccionada = this.tblLista.getSelectedRow();//Identificamos que fila ha sido seleccionada
            try {
                this.txtCodigo.setText(tblLista.getValueAt(filaSeleccionada, 0).toString());
                this.txtNombre.setText(tblLista.getValueAt(filaSeleccionada, 1).toString());
                this.txtEncargado.setText(tblLista.getValueAt(filaSeleccionada, 2).toString());
                this.txtLugar.setText(tblLista.getValueAt(filaSeleccionada, 3).toString());
                this.txtEmpresa.setText(tblLista.getValueAt(filaSeleccionada, 4).toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tblListaKeyReleased

    private void listadeempleadosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeempleadosMouseDragged

    }//GEN-LAST:event_listadeempleadosMouseDragged

    private void listadeempleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeempleadosMouseClicked

    }//GEN-LAST:event_listadeempleadosMouseClicked

    private void listadeempleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeempleadosMousePressed

    }//GEN-LAST:event_listadeempleadosMousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        Opciones.setVisible(false);
        AgregarBT.setVisible(true);
        EliminarBT.setVisible(false);
    }//GEN-LAST:event_btnagregarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btn_agregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar1MouseClicked
        procesar(6);
    }//GEN-LAST:event_btn_agregar1MouseClicked

    private void btn_agregar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar2MouseClicked
        procesar(8);
    }//GEN-LAST:event_btn_agregar2MouseClicked

    private void btn_agregar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar3MouseClicked
        registraAgregarObra();
    }//GEN-LAST:event_btn_agregar3MouseClicked

    private void btn_agregar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar4MouseClicked
        procesar(7);
    }//GEN-LAST:event_btn_agregar4MouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseDragged

    private void btnagregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarMouseClicked

    private void tblLista1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLista1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista1MousePressed

    private void tblLista1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLista1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista1KeyReleased

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void btnagregar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregar1MouseClicked

    private void btnagregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregar1ActionPerformed
        DefaultTableModel tabla = (DefaultTableModel) tblLista.getModel();
        DefaultTableModel tabla1 = (DefaultTableModel) tblLista1.getModel();
        DefaultTableModel tabla2 = (DefaultTableModel) tblLista2.getModel();
        tabla.setRowCount(0);
        tabla2.setRowCount(0);
        z = tabla1.getRowCount();
        boolean a = false;
        for (int i = 0; i < z; i++) {
            a = false;
            Object[] panda = {tblLista1.getValueAt(i, 0), tblLista1.getValueAt(i, 1), tblLista1.getValueAt(i, 2), tblLista1.getValueAt(i, 3), tblLista1.getValueAt(i, 4), tblLista1.getValueAt(i, 5), tblLista1.getValueAt(i, 6)};
            Object[] panda2 = {tblLista1.getValueAt(i, 0), tblLista1.getValueAt(i, 1), tblLista1.getValueAt(i, 2), tblLista1.getValueAt(i, 3), tblLista1.getValueAt(i, 4), tblLista1.getValueAt(i, 5), tblLista1.getValueAt(i, 6), false};
            a = (boolean) tblLista1.getValueAt(i, 7);
            if (a == true) {
                tabla.addRow(panda);
            }
        }

        Opciones.setVisible(true);
        AgregarBT.setVisible(false);
        EliminarBT.setVisible(false);
    }//GEN-LAST:event_btnagregar1ActionPerformed

    private void listadeempleados1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeempleados1MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_listadeempleados1MouseDragged

    private void listadeempleados1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeempleados1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listadeempleados1MouseClicked

    private void listadeempleados1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeempleados1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadeempleados1MousePressed

    private void txtCodigo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo1FocusGained

    private void txtCodigo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo1ActionPerformed

    private void txtNombre1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombre1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1FocusGained

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    private void txtEncargado1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEncargado1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEncargado1FocusGained

    private void txtLugar1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLugar1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugar1FocusGained

    private void txtEmpresa1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmpresa1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresa1FocusGained

    private void btn_agregar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar5MouseClicked

    private void btn_agregar6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar6MouseClicked

    private void btn_agregar7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar7MouseClicked

    private void btn_agregar8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar8MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void tblLista2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLista2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista2MousePressed

    private void tblLista2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLista2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista2KeyReleased

    private void jPanel8MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseDragged

    private void jPanel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MouseClicked

    private void jPanel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel8MousePressed

    private void listadeempleados2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeempleados2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_listadeempleados2MouseDragged

    private void listadeempleados2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeempleados2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listadeempleados2MouseClicked

    private void listadeempleados2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeempleados2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_listadeempleados2MousePressed

    private void txtCodigo2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigo2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo2FocusGained

    private void txtCodigo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigo2ActionPerformed

    private void txtNombre2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombre2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2FocusGained

    private void txtNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2ActionPerformed

    private void txtEncargado2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEncargado2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEncargado2FocusGained

    private void txtLugar2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLugar2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugar2FocusGained

    private void txtEmpresa2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmpresa2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmpresa2FocusGained

    private void btn_agregar9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar9MouseClicked

    private void btn_agregar10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar10MouseClicked

    private void btn_agregar11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar11MouseClicked

    private void btn_agregar12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_agregar12MouseClicked

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MousePressed

    private void btnBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar2ActionPerformed
        DefaultTableModel tabla = (DefaultTableModel) tblLista.getModel();//obtiene un objeto tabla
        DefaultTableModel tabla2 = (DefaultTableModel) tblLista2.getModel();
        z = tabla.getRowCount();
        tabla2.setRowCount(0);
        for (int i = 0; i < z; i++) {
            Object[] panda2 = {tblLista.getValueAt(i, 0), tblLista.getValueAt(i, 1), tblLista.getValueAt(i, 2), tblLista.getValueAt(i, 3),
                tblLista.getValueAt(i, 4), tblLista.getValueAt(i, 5), tblLista.getValueAt(i, 6), false};
            tabla2.addRow(panda2);
        }
        Opciones.setVisible(false);
        AgregarBT.setVisible(false);
        EliminarBT.setVisible(true);
    }//GEN-LAST:event_btnBuscar2ActionPerformed

    private void btnModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar2ActionPerformed
        procesar(2);
    }//GEN-LAST:event_btnModificar2ActionPerformed

    private void TablaLisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaLisKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaLisKeyReleased

    private void btnBuscar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar4ActionPerformed

        DefaultTableModel tabla = (DefaultTableModel) tblLista.getModel();
        DefaultTableModel tabla2 = (DefaultTableModel) tblLista2.getModel();
        boolean a = false;
        int c=0;
        int b = 0;
        b = tabla2.getRowCount();
        for (int i = 0; i < b; i++) {
            a = (boolean) tabla2.getValueAt(i, 7);
//            c = (boolean) tabla2.getValueAt(b - 1, 7);
            if (a == true) {
                c=c+1;
            }
            if (c < 2) {
                if (a == true) {
                    tabla.removeRow(i);
                }
            } else {
                if (i == b - 1) {
                    if (a == true) {
                        tabla.removeRow(i - 1);
                    }
                    break;
                }
                if (a == true) {
                    tabla.removeRow(i);
                }
            }
        }

        Opciones.setVisible(true);
        AgregarBT.setVisible(false);
        EliminarBT.setVisible(false);
    }//GEN-LAST:event_btnBuscar4ActionPerformed

    // ------------switch between colors for Active/Inactive color
    public void resetLblColor(JLabel lbl) {
        lbl.setBackground(new Color(31, 97, 141));
    }

    public void setLblColor(JLabel lbl) {
        lbl.setBackground(new Color(84, 153, 199));
    }

    //-----------End --------
    //Let's create staff options and Avoid data
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarBT;
    private javax.swing.JPanel EliminarBT;
    private javax.swing.JPanel Opciones;
    private javax.swing.JTable TablaLis;
    private javax.swing.JButton btnBuscar2;
    private javax.swing.JButton btnBuscar4;
    private javax.swing.JButton btnModificar2;
    private javax.swing.JLabel btn_agregar;
    private javax.swing.JLabel btn_agregar1;
    private javax.swing.JLabel btn_agregar10;
    private javax.swing.JLabel btn_agregar11;
    private javax.swing.JLabel btn_agregar12;
    private javax.swing.JLabel btn_agregar2;
    private javax.swing.JLabel btn_agregar3;
    private javax.swing.JLabel btn_agregar4;
    private javax.swing.JLabel btn_agregar5;
    private javax.swing.JLabel btn_agregar6;
    private javax.swing.JLabel btn_agregar7;
    private javax.swing.JLabel btn_agregar8;
    private javax.swing.JLabel btn_agregar9;
    private javax.swing.JLabel btn_vista;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnagregar1;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel listadeempleados;
    private javax.swing.JPanel listadeempleados1;
    private javax.swing.JPanel listadeempleados2;
    private javax.swing.JPanel main;
    private javax.swing.JPanel obras;
    private javax.swing.JTable tblLista;
    private javax.swing.JTable tblLista1;
    private javax.swing.JTable tblLista2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigo1;
    private javax.swing.JTextField txtCodigo2;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtEmpresa1;
    private javax.swing.JTextField txtEmpresa2;
    private javax.swing.JTextField txtEncargado;
    private javax.swing.JTextField txtEncargado1;
    private javax.swing.JTextField txtEncargado2;
    private javax.swing.JTextField txtLugar;
    private javax.swing.JTextField txtLugar1;
    private javax.swing.JTextField txtLugar2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    // End of variables declaration//GEN-END:variables

    Obra ob;
    ObraBLL oob = new ObraBLL();
    ObraEmpleadosBLL obemp = new ObraEmpleadosBLL();
    ObraEmpleado obe;
    EmpleadoBLL oemp = new EmpleadoBLL();

    private void procesar(int opcion) {
        String msg = "";
        try {
            switch (opcion) {
                case 5:

                    break;
                case 6:
                    oob.ObraActualizar(leerDatos2());
                    msg = "Obra actualizada con exito";
                    listaObras();
                    nuevaObra();
                    break;
                case 7:
                    oob.ObraEliminar(leerDatos2());
                    listaObras();
                    msg = "Obra eliminada con exito";
                    nuevaObra();
                    break;
                case 8:
                    ListaEmpleados4();
                    verObra();
                    return;
            }
            JOptionPane.showMessageDialog(null, msg);
            listaEmpleados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void listaObras() {
        DefaultTableModel tabla = (DefaultTableModel) TablaLis.getModel();
        tabla.setRowCount(0);
        try {
            List<Obra> lista = oob.ObraListar();
            for (Obra x : oob.ObraListar()) {
                Object[] fila = {x.getCodigo(), x.getNombre(), x.getLugar(), x.getEmpresa(), x.getEncargado()};
                tabla.addRow(fila);
                String palabra =x.getCodigo();
                palabra= palabra.substring(1,5);
                int subnumero = Integer.parseInt(palabra);
                subnumero = subnumero+1;
                txtCodigo.setText("O00"+subnumero);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void listaEmpleados() {

        DefaultTableModel tabla = (DefaultTableModel) tblLista1.getModel();
        tabla.setRowCount(0);
        EmpleadoBLL oemp = new EmpleadoBLL();
        try {
            List<EmpleadoTO> lista = oemp.EmpleadoListar();
            for (EmpleadoTO x : oemp.EmpleadoListar()) {
                Object[] fila = {x.getIdempleado(), x.getNombre(), x.getApellido(), x.getRucdni(), x.getFecha(), x.getTelefono(), x.getCargo(), false};
                tabla.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void verObra() throws Exception {

        ob = oob.ObraBuscar(txtCodigo.getText());
        if (ob != null) {
            txtCodigo.setText(ob.getCodigo());
            txtNombre.setText(ob.getNombre());
            txtEmpresa.setText(ob.getEmpresa());
            txtLugar.setText(ob.getLugar());
            txtEncargado.setText(ob.getEncargado());
            JOptionPane.showMessageDialog(null, "Obra encontrada con exito");
        } else {
            JOptionPane.showMessageDialog(null, "Obra no existe");
        }
    }

    private Obra leerDatos2() {
        ob = new Obra(txtCodigo.getText(), txtNombre.getText(), txtLugar.getText(), txtEmpresa.getText(), txtEncargado.getText());
        return ob;
    }

    private void registraAgregarObra() {
        try {
            oob.ObraAdicionar(leerDatos2());
            z = tblLista.getRowCount();
            for (int i = 0; i < z; i++) {
                obe = new ObraEmpleado((String) tblLista.getValueAt(i, 0), txtCodigo.getText());
                obemp.ObraEmpleadosAdicionar(obe);
            }
            JOptionPane.showMessageDialog(this, "Registro de obra completado");
            nuevaObra();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        listaObras();
    }

    private void nuevaObra() {
        txtCodigo.setText("");
        txtEmpresa.setText("");
        txtEncargado.setText("");
        txtLugar.setText("");
        txtNombre.setText("");
        DefaultTableModel tabla = (DefaultTableModel) tblLista.getModel();
        DefaultTableModel tabla1 = (DefaultTableModel) tblLista1.getModel();
        DefaultTableModel tabla2 = (DefaultTableModel) tblLista2.getModel();
        tabla.setRowCount(0);

    }

    private void ListaEmpleados4() {
        DefaultTableModel tabla = (DefaultTableModel) tblLista.getModel();
        tabla.setRowCount(0);
        try {
            codigo = txtCodigo.getText();
            List<EmpleadoTO> lista = oemp.EmpleadoListar3(codigo);
            for (EmpleadoTO x : oemp.EmpleadoListar3(codigo)) {
                Object[] fila = {x.getIdempleado(), x.getNombre(), x.getApellido(), x.getRucdni(), x.getFecha(), x.getTelefono(), x.getCargo(), false};
                tabla.addRow(fila);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }
}
