/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import componentes.FadeEffect;
import controller.EmpleadoBLL;
import controller.ObraBLL;
import entity.EmpleadoTO;
import entity.Obra;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author proxc
 */
public class viewEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form Home15
     */
    public viewEmpleados() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        listaEmpleados();
        listaEmpleados2();
        listaEmpleados3();

        vacio.setVisible(true);
        nombre2.setVisible(false);
        cargo2.setVisible(false);
    }
    int i;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_vista = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        empleados = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btn_nombre = new javax.swing.JLabel();
        btn_cargo = new javax.swing.JLabel();
        btn_todo = new javax.swing.JLabel();
        vacio = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaLista = new javax.swing.JTable();
        nombre2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        TablaLista4 = new javax.swing.JTable();
        txtRellene = new javax.swing.JTextField();
        cargo2 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        TablaLista3 = new javax.swing.JTable();
        txtRellene1 = new javax.swing.JTextField();
        EliminarVarios = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar2 = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        txtIdEmpleado1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txtNombre1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        txtApellido1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        txtDNI1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        txtFecha1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        txtTelefono1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        txtCargo1 = new javax.swing.JTextField();
        btnAgregar3 = new javax.swing.JButton();
        btnBuscar3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblLista1 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        Agregar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtIdEmpleado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtApellido = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtDNI = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        txtFecha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtCargo = new javax.swing.JTextField();
        btnAgregar1 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        main.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(31, 97, 147));
        header.setPreferredSize(new java.awt.Dimension(838, 200));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 116, -1, -1));

        btn_vista.setBackground(new java.awt.Color(84, 153, 199));
        btn_vista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista.setText("Inicio");
        btn_vista.setOpaque(true);
        btn_vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vistaMouseClicked(evt);
            }
        });
        header.add(btn_vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 146, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 62, 65, 48));

        btn_agregar.setBackground(new java.awt.Color(31, 97, 147));
        btn_agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar.setText("Opciones");
        btn_agregar.setOpaque(true);
        btn_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarMouseClicked(evt);
            }
        });
        header.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 146, 30));

        jLabel3.setBackground(new java.awt.Color(31, 97, 147));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 32, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Empleados");
        header.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 370, 80));

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DRYWALL FAMILY");
        header.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BGAB_icon_211x211.png"))); // NOI18N
        header.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, 160));

        home.setLayout(new java.awt.CardLayout());

        empleados.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(31, 97, 147));
        jPanel6.setForeground(new java.awt.Color(255, 204, 204));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Lista de Empleados");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 340, 30));

        btn_nombre.setBackground(new java.awt.Color(31, 97, 147));
        btn_nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_nombre.setForeground(new java.awt.Color(255, 255, 255));
        btn_nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_nombre.setText("Nombre");
        btn_nombre.setOpaque(true);
        btn_nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nombreMouseClicked(evt);
            }
        });
        jPanel6.add(btn_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 130, 30));

        btn_cargo.setBackground(new java.awt.Color(31, 97, 147));
        btn_cargo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_cargo.setForeground(new java.awt.Color(255, 255, 255));
        btn_cargo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_cargo.setText("Cargo");
        btn_cargo.setOpaque(true);
        btn_cargo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cargoMouseClicked(evt);
            }
        });
        jPanel6.add(btn_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 130, 30));

        btn_todo.setBackground(new java.awt.Color(84, 153, 199));
        btn_todo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_todo.setForeground(new java.awt.Color(255, 255, 255));
        btn_todo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_todo.setText("Todos");
        btn_todo.setOpaque(true);
        btn_todo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_todoMouseClicked(evt);
            }
        });
        jPanel6.add(btn_todo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 130, 30));

        vacio.setBackground(new java.awt.Color(31, 97, 147));
        vacio.setForeground(new java.awt.Color(102, 102, 255));

        TablaLista.setAutoCreateRowSorter(true);
        TablaLista.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TablaLista.setForeground(new java.awt.Color(102, 102, 102));
        TablaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "DNI", "F / N", "Telefono", "Cargo"
            }
        ));
        TablaLista.setGridColor(new java.awt.Color(51, 51, 51));
        TablaLista.setSelectionBackground(new java.awt.Color(0, 51, 204));
        TablaLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaListaMousePressed(evt);
            }
        });
        TablaLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaListaKeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(TablaLista);

        javax.swing.GroupLayout vacioLayout = new javax.swing.GroupLayout(vacio);
        vacio.setLayout(vacioLayout);
        vacioLayout.setHorizontalGroup(
            vacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vacioLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        vacioLayout.setVerticalGroup(
            vacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vacioLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel6.add(vacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1530, 460));

        nombre2.setBackground(new java.awt.Color(31, 97, 147));
        nombre2.setForeground(new java.awt.Color(31, 97, 147));

        TablaLista4.setAutoCreateRowSorter(true);
        TablaLista4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TablaLista4.setForeground(new java.awt.Color(102, 102, 102));
        TablaLista4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "DNI", "F / N", "Telefono", "Cargo"
            }
        ));
        TablaLista4.setGridColor(new java.awt.Color(51, 51, 51));
        TablaLista4.setSelectionBackground(new java.awt.Color(0, 51, 204));
        TablaLista4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaLista4MousePressed(evt);
            }
        });
        TablaLista4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaLista4KeyReleased(evt);
            }
        });
        jScrollPane9.setViewportView(TablaLista4);

        txtRellene.setText("Ingrese el nombre");
        txtRellene.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRelleneFocusGained(evt);
            }
        });
        txtRellene.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRelleneKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout nombre2Layout = new javax.swing.GroupLayout(nombre2);
        nombre2.setLayout(nombre2Layout);
        nombre2Layout.setHorizontalGroup(
            nombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nombre2Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addGroup(nombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRellene, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(408, Short.MAX_VALUE))
        );
        nombre2Layout.setVerticalGroup(
            nombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nombre2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtRellene, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel6.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1530, 460));

        cargo2.setBackground(new java.awt.Color(31, 97, 147));
        cargo2.setForeground(new java.awt.Color(31, 97, 147));

        TablaLista3.setAutoCreateRowSorter(true);
        TablaLista3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        TablaLista3.setForeground(new java.awt.Color(102, 102, 102));
        TablaLista3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "DNI", "F / N", "Telefono", "Cargo"
            }
        ));
        TablaLista3.setGridColor(new java.awt.Color(51, 51, 51));
        TablaLista3.setSelectionBackground(new java.awt.Color(0, 51, 204));
        TablaLista3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TablaLista3MousePressed(evt);
            }
        });
        TablaLista3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TablaLista3KeyReleased(evt);
            }
        });
        jScrollPane8.setViewportView(TablaLista3);

        txtRellene1.setText("Ingrese el cargo");
        txtRellene1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRellene1FocusGained(evt);
            }
        });
        txtRellene1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRellene1ActionPerformed(evt);
            }
        });
        txtRellene1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRellene1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout cargo2Layout = new javax.swing.GroupLayout(cargo2);
        cargo2.setLayout(cargo2Layout);
        cargo2Layout.setHorizontalGroup(
            cargo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cargo2Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addGroup(cargo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRellene1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(408, Short.MAX_VALUE))
        );
        cargo2Layout.setVerticalGroup(
            cargo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cargo2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtRellene1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel6.add(cargo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1530, 460));

        javax.swing.GroupLayout empleadosLayout = new javax.swing.GroupLayout(empleados);
        empleados.setLayout(empleadosLayout);
        empleadosLayout.setHorizontalGroup(
            empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empleadosLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 515, Short.MAX_VALUE))
        );
        empleadosLayout.setVerticalGroup(
            empleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        home.add(empleados, "card3");

        EliminarVarios.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar2.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar2.setText("Buscar");
        btnAgregar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        btnModificar1.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Datos del Empleado");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 40));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 320, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Codigo:");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 10));

        txtIdEmpleado1.setText("ingrese codigo");
        txtIdEmpleado1.setBorder(null);
        txtIdEmpleado1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdEmpleado1FocusGained(evt);
            }
        });
        txtIdEmpleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleado1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdEmpleado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Nombre:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, 20));

        txtNombre1.setText("ingrese nombre");
        txtNombre1.setBorder(null);
        txtNombre1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombre1FocusGained(evt);
            }
        });
        jPanel2.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Apellido:");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 10));

        txtApellido1.setText("ingrese apellido");
        txtApellido1.setBorder(null);
        txtApellido1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellido1FocusGained(evt);
            }
        });
        jPanel2.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("DNI:");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, -1));

        txtDNI1.setText("ingrese dni");
        txtDNI1.setBorder(null);
        txtDNI1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDNI1FocusGained(evt);
            }
        });
        jPanel2.add(txtDNI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Fecha de nacimiento:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 90, 10));

        txtFecha1.setText("ingrese fecha");
        txtFecha1.setBorder(null);
        txtFecha1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFecha1FocusGained(evt);
            }
        });
        jPanel2.add(txtFecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 90, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Telefono:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 80, 10));

        txtTelefono1.setText("ingrese telefono");
        txtTelefono1.setBorder(null);
        txtTelefono1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefono1FocusGained(evt);
            }
        });
        jPanel2.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 80, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setText("Cargo:");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 90, -1));

        txtCargo1.setText("ingrese cargo");
        txtCargo1.setBorder(null);
        txtCargo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCargo1FocusGained(evt);
            }
        });
        jPanel2.add(txtCargo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 90, -1));

        btnAgregar3.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar3.setText("Agregar");
        btnAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        btnBuscar3.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar3.setText("Eliminar");
        btnBuscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jPanel5.setBackground(new java.awt.Color(31, 97, 147));
        jPanel5.setForeground(new java.awt.Color(255, 204, 204));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLista1.setAutoCreateRowSorter(true);
        tblLista1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblLista1.setForeground(new java.awt.Color(102, 102, 102));
        tblLista1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "DNI", "F / N", "Telefono", "Cargo", "Eliminar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLista1.setGridColor(new java.awt.Color(51, 51, 51));
        tblLista1.setSelectionBackground(new java.awt.Color(26, 82, 118));
        tblLista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLista1MousePressed(evt);
            }
        });
        tblLista1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblLista1KeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tblLista1);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 660, 260));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Lista de Empleados");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        javax.swing.GroupLayout EliminarVariosLayout = new javax.swing.GroupLayout(EliminarVarios);
        EliminarVarios.setLayout(EliminarVariosLayout);
        EliminarVariosLayout.setHorizontalGroup(
            EliminarVariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarVariosLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(681, Short.MAX_VALUE))
        );
        EliminarVariosLayout.setVerticalGroup(
            EliminarVariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        home.add(EliminarVarios, "card3");

        Agregar.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Buscar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Datos del Empleado");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 40));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 320, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Codigo:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jSeparator2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jSeparator2FocusGained(evt);
            }
        });
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 10));

        txtIdEmpleado.setBorder(null);
        txtIdEmpleado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdEmpleadoFocusGained(evt);
            }
        });
        txtIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Nombre:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, 20));

        txtNombre.setBorder(null);
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreFocusGained(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Apellido:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 190, 10));

        txtApellido.setBorder(null);
        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidoFocusGained(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("DNI:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, -1));

        txtDNI.setBorder(null);
        txtDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDNIFocusGained(evt);
            }
        });
        jPanel1.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 80, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fecha de nacimiento:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 90, 10));

        txtFecha.setBorder(null);
        txtFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFechaFocusGained(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Telefono:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 80, 10));

        txtTelefono.setBorder(null);
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusGained(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 80, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Cargo:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 90, -1));

        txtCargo.setBorder(null);
        txtCargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCargoFocusGained(evt);
            }
        });
        jPanel1.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 90, -1));

        btnAgregar1.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar1.setText("Guardar");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Eliminar ");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        jPanel4.setBackground(new java.awt.Color(31, 97, 147));
        jPanel4.setForeground(new java.awt.Color(255, 204, 204));
        jPanel4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel4MouseDragged(evt);
            }
        });
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel4MousePressed(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLista.setAutoCreateRowSorter(true);
        tblLista.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblLista.setForeground(new java.awt.Color(102, 102, 102));
        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "DNI", "F / N", "Telefono", "Cargo"
            }
        ));
        tblLista.setGridColor(new java.awt.Color(51, 51, 51));
        tblLista.setSelectionBackground(new java.awt.Color(0, 51, 204));
        tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblListaMousePressed(evt);
            }
        });
        tblLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblListaKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblLista);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 660, 260));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lista de Empleados");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        javax.swing.GroupLayout AgregarLayout = new javax.swing.GroupLayout(Agregar);
        Agregar.setLayout(AgregarLayout);
        AgregarLayout.setHorizontalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AgregarLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(681, Short.MAX_VALUE))
        );
        AgregarLayout.setVerticalGroup(
            AgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        home.add(Agregar, "card3");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MousePressed

    }//GEN-LAST:event_jPanel4MousePressed

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked

    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseDragged

    }//GEN-LAST:event_jPanel4MouseDragged

    private void tblListaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListaKeyReleased
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            int filaSeleccionada = this.tblLista.getSelectedRow();//Identificamos que fila ha sido seleccionada
            //cuando voy a ingresar algo que te pueda votar error
            try {
                this.txtIdEmpleado.setText(tblLista.getValueAt(filaSeleccionada, 0).toString());
                this.txtNombre.setText(tblLista.getValueAt(filaSeleccionada, 1).toString());
                this.txtApellido.setText(tblLista.getValueAt(filaSeleccionada, 2).toString());
                this.txtDNI.setText(tblLista.getValueAt(filaSeleccionada, 3).toString());
                this.txtFecha.setText(tblLista.getValueAt(filaSeleccionada, 4).toString());
                this.txtTelefono.setText(tblLista.getValueAt(filaSeleccionada, 5).toString());
                this.txtCargo.setText(tblLista.getValueAt(filaSeleccionada, 6).toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_tblListaKeyReleased

    private void tblListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMousePressed
        int filaSeleccionada = this.tblLista.getSelectedRow();//Identificamos que fila ha sido seleccionada

        try {
            this.txtIdEmpleado.setText(tblLista.getValueAt(filaSeleccionada, 0).toString());
            this.txtNombre.setText(tblLista.getValueAt(filaSeleccionada, 1).toString());
            this.txtApellido.setText(tblLista.getValueAt(filaSeleccionada, 2).toString());
            this.txtDNI.setText(tblLista.getValueAt(filaSeleccionada, 3).toString());
            this.txtFecha.setText(tblLista.getValueAt(filaSeleccionada, 4).toString());
            this.txtTelefono.setText(tblLista.getValueAt(filaSeleccionada, 5).toString());
            this.txtCargo.setText(tblLista.getValueAt(filaSeleccionada, 6).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tblListaMousePressed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed

    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged

    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed

        procesar(1);
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void txtCargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCargoFocusGained

    }//GEN-LAST:event_txtCargoFocusGained

    private void txtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusGained

    }//GEN-LAST:event_txtTelefonoFocusGained

    private void txtFechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFechaFocusGained

    }//GEN-LAST:event_txtFechaFocusGained

    private void txtDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNIFocusGained

    }//GEN-LAST:event_txtDNIFocusGained

    private void txtApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusGained

    }//GEN-LAST:event_txtApellidoFocusGained

    private void txtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusGained

    }//GEN-LAST:event_txtNombreFocusGained

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed

    private void txtIdEmpleadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdEmpleadoFocusGained

    }//GEN-LAST:event_txtIdEmpleadoFocusGained

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        procesar(3);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        procesar(2);
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        procesar(4);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseDragged

    private void txtRellene1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRellene1KeyReleased
        listaEmpleadosCargo();
    }//GEN-LAST:event_txtRellene1KeyReleased

    private void txtRellene1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRellene1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRellene1ActionPerformed

    private void txtRellene1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRellene1FocusGained
        txtRellene1.setText("");
    }//GEN-LAST:event_txtRellene1FocusGained

    private void TablaLista3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaLista3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaLista3KeyReleased

    private void TablaLista3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaLista3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaLista3MousePressed

    private void txtRelleneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRelleneKeyReleased
        listaEmpleadosNombre();
    }//GEN-LAST:event_txtRelleneKeyReleased

    private void txtRelleneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRelleneFocusGained
        txtRellene.setText("");
    }//GEN-LAST:event_txtRelleneFocusGained

    private void TablaLista4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaLista4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaLista4KeyReleased

    private void TablaLista4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaLista4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaLista4MousePressed

    private void TablaListaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaListaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaListaKeyReleased

    private void TablaListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaListaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaListaMousePressed

    private void btn_todoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_todoMouseClicked
        setLblColor(btn_todo);
        resetLblColor(btn_nombre);
        resetLblColor(btn_cargo);
        vacio.setVisible(true);
        nombre2.setVisible(false);
        cargo2.setVisible(false);
    }//GEN-LAST:event_btn_todoMouseClicked

    private void btn_cargoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cargoMouseClicked
        setLblColor(btn_cargo);
        resetLblColor(btn_todo);
        resetLblColor(btn_nombre);
        cargo2.setVisible(true);
        nombre2.setVisible(false);
        vacio.setVisible(false);
    }//GEN-LAST:event_btn_cargoMouseClicked

    private void btn_nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nombreMouseClicked
        setLblColor(btn_nombre);
        resetLblColor(btn_todo);
        resetLblColor(btn_cargo);
        nombre2.setVisible(true);
        vacio.setVisible(false);
        cargo2.setVisible(false);

    }//GEN-LAST:event_btn_nombreMouseClicked

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_headerMouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarMouseClicked
        setLblColor(btn_agregar);
        resetLblColor(btn_vista);
        Agregar.setVisible(true);
        empleados.setVisible(false);
    }//GEN-LAST:event_btn_agregarMouseClicked

    private void btn_vistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vistaMouseClicked
        // TODO add your handling code here:

        setLblColor(btn_vista);
        resetLblColor(btn_agregar);
        //switch bettween Jpanels
        EliminarVarios.setVisible(false);
        Agregar.setVisible(false);

        empleados.setVisible(true);

    }//GEN-LAST:event_btn_vistaMouseClicked

    private void btnAgregar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar2ActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void txtIdEmpleado1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdEmpleado1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleado1FocusGained

    private void txtIdEmpleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleado1ActionPerformed

    private void txtNombre1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombre1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1FocusGained

    private void txtApellido1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellido1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1FocusGained

    private void txtDNI1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNI1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNI1FocusGained

    private void txtFecha1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFecha1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFecha1FocusGained

    private void txtTelefono1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefono1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono1FocusGained

    private void txtCargo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCargo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargo1FocusGained

    private void btnAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregar3ActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void tblLista1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLista1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista1MousePressed

    private void tblLista1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLista1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista1KeyReleased

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel5MousePressed

    private void btnBuscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar3ActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void jSeparator2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jSeparator2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jSeparator2FocusGained
    int xx;
    int xy;

    // ------------switch between colors for Active/Inactive color
    public void resetLblColor(JLabel lbl) {
        lbl.setBackground(new Color(31, 97, 141));
    }

    public void setLblColor(JLabel lbl) {
        lbl.setBackground(new Color(84, 153, 199));
    }

    //-----------End --------
    //Let's create staff options and Avoid data
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agregar;
    private javax.swing.JPanel EliminarVarios;
    private javax.swing.JTable TablaLista;
    private javax.swing.JTable TablaLista3;
    private javax.swing.JTable TablaLista4;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnAgregar2;
    private javax.swing.JButton btnAgregar3;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar3;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JLabel btn_agregar;
    private javax.swing.JLabel btn_cargo;
    private javax.swing.JLabel btn_nombre;
    private javax.swing.JLabel btn_todo;
    private javax.swing.JLabel btn_vista;
    private javax.swing.JPanel cargo2;
    private javax.swing.JPanel empleados;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JPanel main;
    private javax.swing.JPanel nombre2;
    private javax.swing.JTable tblLista;
    private javax.swing.JTable tblLista1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCargo1;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDNI1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFecha1;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtIdEmpleado1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtRellene;
    private javax.swing.JTextField txtRellene1;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JPanel vacio;
    // End of variables declaration//GEN-END:variables
   EmpleadoBLL oemp = new EmpleadoBLL();
    EmpleadoTO emp;
    Obra ob;
    ObraBLL oob = new ObraBLL();

    private void procesar(int opcion) {
        String msg = "";
        try {
            switch (opcion) {
                case 1:
                    oemp.EmpleadoAdicionar(leerDatos());
                    msg = "Empleado registrado con exito";
                    listaEmpleados();
                    listaEmpleados2();
                    listaEmpleados3();
                    break;
                case 2:
                    oemp.EmpleadoActualizar(leerDatos());
                    msg = "Empleado actualizado con exito";
                    listaEmpleados();
                    listaEmpleados2();
                    listaEmpleados3();
                    break;
                case 3:
                    oemp.EmpleadoEliminar(leerDatos());
                    msg = "Empleado eliminado con exito";
                    listaEmpleados();
                    listaEmpleados2();
                    listaEmpleados3();
                    break;
                case 4:
                    verEmpleado();
                    return;
            }
            JOptionPane.showMessageDialog(null, msg);
            listaEmpleados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void listaEmpleados() {

        DefaultTableModel tabla = (DefaultTableModel) TablaLista.getModel();
        DefaultTableModel tabla2 = (DefaultTableModel) tblLista.getModel();
        tabla.setRowCount(0);
        try {
            List<EmpleadoTO> lista = oemp.EmpleadoListar();
            for (EmpleadoTO x : oemp.EmpleadoListar()) {
                Object[] fila = {x.getIdempleado(), x.getNombre(), x.getApellido(), x.getRucdni(), x.getFecha(), x.getTelefono(), x.getCargo()};
                tabla.addRow(fila);
                tabla2.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void listaEmpleados2() {

        DefaultTableModel tabla2 = (DefaultTableModel) tblLista.getModel();
        tabla2.setRowCount(0);
        try {
            List<EmpleadoTO> lista = oemp.EmpleadoListar();
            for (EmpleadoTO x : oemp.EmpleadoListar()) {
                Object[] fila = {x.getIdempleado(), x.getNombre(), x.getApellido(), x.getRucdni(), x.getFecha(), x.getTelefono(), x.getCargo()};
                tabla2.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }


    private void listaEmpleados3() {

        DefaultTableModel tabla = (DefaultTableModel) tblLista1.getModel();
        tabla.setRowCount(0);
        try {
            List<EmpleadoTO> lista = oemp.EmpleadoListar();
            for (EmpleadoTO x : oemp.EmpleadoListar()) {
                Object[] fila = {x.getIdempleado(), x.getNombre(), x.getApellido(), x.getRucdni(), x.getFecha(), x.getTelefono(), x.getCargo(), false};
                tabla.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void listaEmpleadosNombre() {

        DefaultTableModel tabla = (DefaultTableModel) TablaLista4.getModel();
        tabla.setRowCount(0);
        try {
            List<EmpleadoTO> lista = oemp.EmpleadoListar(txtRellene.getText());
            for (EmpleadoTO x : lista) {
                Object[] fila = {x.getIdempleado(), x.getNombre(), x.getApellido(),
                    x.getRucdni(), x.getFecha(), x.getTelefono(), x.getCargo()};
                tabla.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void listaEmpleadosCargo() {

        DefaultTableModel tabla = (DefaultTableModel) TablaLista3.getModel();
        tabla.setRowCount(0);
        try {
            //llema al metodo empleado listar
            List<EmpleadoTO> lista = oemp.EmpleadoListar2(txtRellene1.getText());
            for (EmpleadoTO x : lista) {
                Object[] fila = {x.getIdempleado(), x.getNombre(), x.getApellido(),
                    x.getRucdni(), x.getFecha(), x.getTelefono(), x.getCargo()};
                tabla.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private EmpleadoTO leerDatos() {
        emp = new EmpleadoTO(txtIdEmpleado.getText(), txtNombre.getText(), txtApellido.getText(), txtDNI.getText(), txtFecha.getText(), txtTelefono.getText(), txtCargo.getText());
        return emp;
    }

    private void verEmpleado() throws Exception {
        emp = oemp.EmpleadoBuscar(txtIdEmpleado.getText());
        if (emp != null) {
            //se creo un objeto que se rrelenara con el metodo empleado buscar 
            txtIdEmpleado.setText(emp.getIdempleado());
            txtNombre.setText(emp.getNombre());
            txtCargo.setText(emp.getCargo());
            txtFecha.setText(emp.getFecha());
            txtTelefono.setText(emp.getTelefono());
            txtDNI.setText(emp.getRucdni());
            txtCargo.setText(emp.getTelefono());

        } else {
            JOptionPane.showMessageDialog(null, "Empleado no existe");
        }
    }

}
