/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import controller.AsistenciaBLL;
import controller.EmpleadoBLL;
import controller.ObraBLL;
import controller.ObraEmpleadosBLL;
import entity.AsistenciaTO;
import entity.EmpleadoTO;
import entity.Obra;
import entity.ObraEmpleado;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author proxc
 */
public class viewPagoGrafica extends javax.swing.JFrame implements Runnable {

    int z;
    TableColumn agregarColumn;
    String codigo;
    String idempleado1;
    String hora, minutos, segundos;
    Thread hilo;

    public viewPagoGrafica() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);

//                lbfecha.setText(fecha());
        hilo = new Thread((Runnable) this);
        hilo.start();
        listaObras();
        Persona.setVisible(false);
        cargaCombos();
  
    }

    public void hora() {
        Calendar calendario = new GregorianCalendar();
        Date horaactual = new Date();
        calendario.setTime(horaactual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    public void run(){
        Thread currend =Thread.currentThread();
       // while(currend==hilo){
         //   hora();
           // lbhora.setText(hora+":" + minutos+":"+segundos);
           for (int i=1;i>0;i++){
               if(i>0){
                 hora();
//           lbhora.setText(hora+":" + minutos+":"+segundos);  
               }
               
        
        }
    }
        public static String fecha(){
        Date fecha=new Date ();
        SimpleDateFormat formatofecha = new SimpleDateFormat ("dd/MM/YYYY");
        return formatofecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_vista = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreObra = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_vista3 = new javax.swing.JLabel();
        btn_vista4 = new javax.swing.JLabel();
        btn_vista5 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblLista5 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        btn_vista9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btn_vista7 = new javax.swing.JLabel();
        btn_vista8 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cboPago = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        cboObra = new javax.swing.JComboBox<>();
        btn_vista10 = new javax.swing.JLabel();
        Persona = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblLista2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        btn_vista2 = new javax.swing.JLabel();
        btn_vista6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLista1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        main.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(31, 97, 141));
        header.setPreferredSize(new java.awt.Dimension(838, 200));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 116, -1, -1));

        btn_vista.setBackground(new java.awt.Color(84, 153, 199));
        btn_vista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista.setText("Orden de pago");
        btn_vista.setOpaque(true);
        btn_vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vistaMouseClicked(evt);
            }
        });
        header.add(btn_vista, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 170, 30));

        jLabel3.setBackground(new java.awt.Color(31, 97, 141));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 32, -1));

        txtNombreObra.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreObra.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        txtNombreObra.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreObra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNombreObra.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        header.add(txtNombreObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 500, 100));

        jLabel17.setText("jLabel17");
        header.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BGAB_icon_211x211.png"))); // NOI18N
        header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 220, 160));

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DRYWALL FAMILY");
        header.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pago");
        header.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 190, 100));

        btn_vista3.setBackground(new java.awt.Color(31, 97, 141));
        btn_vista3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista3.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista3.setText("Por persona");
        btn_vista3.setOpaque(true);
        btn_vista3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vista3MouseClicked(evt);
            }
        });
        header.add(btn_vista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 170, 30));

        btn_vista4.setBackground(new java.awt.Color(31, 97, 141));
        btn_vista4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista4.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista4.setText("Por semana");
        btn_vista4.setOpaque(true);
        btn_vista4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vista4MouseClicked(evt);
            }
        });
        header.add(btn_vista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 170, 30));

        btn_vista5.setBackground(new java.awt.Color(31, 97, 141));
        btn_vista5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista5.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista5.setText("Por mes");
        btn_vista5.setOpaque(true);
        btn_vista5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vista5MouseClicked(evt);
            }
        });
        header.add(btn_vista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 170, 30));

        home.setLayout(new java.awt.CardLayout());

        Inicio.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(26, 82, 118));
        jPanel7.setForeground(new java.awt.Color(255, 204, 204));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(26, 82, 118));
        jPanel8.setForeground(new java.awt.Color(26, 82, 118));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel24.setBackground(new java.awt.Color(31, 97, 147));
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("X");
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 32, -1));

        jLabel25.setBackground(new java.awt.Color(31, 97, 147));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("X");
        jLabel25.setOpaque(true);
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 32, -1));

        tblLista5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Horas", "Pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLista5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLista5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLista5MousePressed(evt);
            }
        });
        tblLista5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblLista5KeyReleased(evt);
            }
        });
        jScrollPane8.setViewportView(tblLista5);

        jPanel8.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 640, 320));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Orden de pago");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 180, 30));

        btn_vista9.setBackground(new java.awt.Color(31, 97, 141));
        btn_vista9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista9.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista9.setText("Editar");
        btn_vista9.setOpaque(true);
        btn_vista9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vista9MouseClicked(evt);
            }
        });
        jPanel8.add(btn_vista9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 170, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 790, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 150, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 790, 710));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(26, 82, 118));
        jLabel23.setText("Tipo de pago:");

        btn_vista7.setBackground(new java.awt.Color(31, 97, 141));
        btn_vista7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista7.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista7.setText("Previsualizar");
        btn_vista7.setOpaque(true);
        btn_vista7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vista7MouseClicked(evt);
            }
        });

        btn_vista8.setBackground(new java.awt.Color(31, 97, 141));
        btn_vista8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista8.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista8.setText("Imprimir ");
        btn_vista8.setOpaque(true);
        btn_vista8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vista8MouseClicked(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(26, 82, 118));
        jLabel27.setText("Control de pago");

        cboPago.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboPago.setForeground(new java.awt.Color(26, 82, 118));
        cboPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Por persona", "Por semana", "Por mes", " " }));
        cboPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPagoActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(26, 82, 118));
        jLabel28.setText("Obra:");

        cboObra.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        cboObra.setForeground(new java.awt.Color(26, 82, 118));
        cboObra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Por persona", "Por semana", "Por mes", " " }));
        cboObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboObraActionPerformed(evt);
            }
        });

        btn_vista10.setBackground(new java.awt.Color(31, 97, 141));
        btn_vista10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista10.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista10.setText("Agregar");
        btn_vista10.setOpaque(true);
        btn_vista10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vista10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboObra, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPago, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel27)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(btn_vista7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_vista8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_vista10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboObra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(btn_vista10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_vista7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vista8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 647, Short.MAX_VALUE))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        home.add(Inicio, "card3");

        Persona.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(26, 82, 118));
        jPanel6.setForeground(new java.awt.Color(255, 204, 204));
        jPanel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel6MouseDragged(evt);
            }
        });
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Lista de Obras");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, 30));

        tblLista.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblLista.setForeground(new java.awt.Color(51, 51, 51));
        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLista.setGridColor(new java.awt.Color(255, 255, 255));
        tblLista.setRowHeight(20);
        tblLista.setSelectionBackground(new java.awt.Color(26, 82, 118));
        tblLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblListaMousePressed(evt);
            }
        });
        tblLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblListaKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tblLista);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 310, 310));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblLista2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Fecha", "Horas", "Pago", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLista2.getTableHeader().setReorderingAllowed(false);
        tblLista2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLista2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLista2MousePressed(evt);
            }
        });
        tblLista2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblLista2KeyReleased(evt);
            }
        });
        jScrollPane5.setViewportView(tblLista2);
        if (tblLista2.getColumnModel().getColumnCount() > 0) {
            tblLista2.getColumnModel().getColumn(5).setMaxWidth(30);
        }

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(26, 82, 118));
        jLabel18.setText("Lista de horas trabajadas");

        btn_vista2.setBackground(new java.awt.Color(31, 97, 141));
        btn_vista2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista2.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista2.setText("Agregar");
        btn_vista2.setOpaque(true);
        btn_vista2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vista2MouseClicked(evt);
            }
        });

        btn_vista6.setBackground(new java.awt.Color(31, 97, 141));
        btn_vista6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_vista6.setForeground(new java.awt.Color(255, 255, 255));
        btn_vista6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_vista6.setText("Pagar");
        btn_vista6.setOpaque(true);
        btn_vista6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_vista6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btn_vista2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(btn_vista6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_vista2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vista6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(26, 82, 118));
        jPanel4.setForeground(new java.awt.Color(26, 82, 118));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel19.setBackground(new java.awt.Color(31, 97, 147));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("X");
        jLabel19.setOpaque(true);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 32, -1));

        jLabel20.setBackground(new java.awt.Color(31, 97, 147));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("X");
        jLabel20.setOpaque(true);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 32, -1));

        tblLista1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblLista1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLista1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLista1MousePressed(evt);
            }
        });
        tblLista1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblLista1KeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tblLista1);
        if (tblLista1.getColumnModel().getColumnCount() > 0) {
            tblLista1.getColumnModel().getColumn(0).setHeaderValue("Codigo");
        }

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 320, 320));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Lista de Empleados");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 180, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 150, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 990, 710));

        javax.swing.GroupLayout PersonaLayout = new javax.swing.GroupLayout(Persona);
        Persona.setLayout(PersonaLayout);
        PersonaLayout.setHorizontalGroup(
            PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 647, Short.MAX_VALUE))
        );
        PersonaLayout.setVerticalGroup(
            PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        home.add(Persona, "card3");

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:


    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_headerMouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btn_vistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vistaMouseClicked
        // TODO add your handling code here:
        listaObras();
        setLblColor(btn_vista);
        Inicio.setVisible(true);
        Persona.setVisible(false);
        

    }//GEN-LAST:event_btn_vistaMouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseDragged

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void tblListaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMousePressed

    }//GEN-LAST:event_tblListaMousePressed

    private void tblListaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblListaKeyReleased
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN) || (evt.getKeyCode() == KeyEvent.VK_UP)) {
            int filaSeleccionada = this.tblLista.getSelectedRow();//Identificamos que fila ha sido seleccionada
            try {
//                this.txtCodigo.setText("-" + tblLista.getValueAt(filaSeleccionada, 0).toString());
                this.txtNombreObra.setText(tblLista.getValueAt(filaSeleccionada, 1).toString());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_tblListaKeyReleased

    private void tblLista1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLista1KeyReleased

    }//GEN-LAST:event_tblLista1KeyReleased

    private void tblLista1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLista1MousePressed

    }//GEN-LAST:event_tblLista1MousePressed

    private void tblLista1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLista1MouseClicked

//        listaAsistencia();
    }//GEN-LAST:event_tblLista1MouseClicked

    private void tblListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaMouseClicked
             int filaSeleccionada = this.tblLista.getSelectedRow();//Identificamos que fila ha sido seleccionada

        try {
//            this.txtCodigo.setText(tblLista.getValueAt(filaSeleccionada, 0).toString());
            codigo = tblLista.getValueAt(filaSeleccionada, 0).toString();
            this.txtNombreObra.setText(tblLista.getValueAt(filaSeleccionada, 1).toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al leer datos de la tabla", "Error", JOptionPane.WARNING_MESSAGE);
        }
        listaEmpleados();
    }//GEN-LAST:event_tblListaMouseClicked

    private void tblLista2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLista2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista2MouseClicked

    private void tblLista2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLista2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista2MousePressed

    private void tblLista2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLista2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista2KeyReleased

    private void btn_vista2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vista2MouseClicked

    private void btn_vista3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vista3MouseClicked

    private void btn_vista4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vista4MouseClicked

    private void btn_vista5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vista5MouseClicked

    private void btn_vista6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vista6MouseClicked

    private void btn_vista7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vista7MouseClicked

    private void btn_vista8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vista8MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void tblLista5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLista5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista5MouseClicked

    private void tblLista5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLista5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista5MousePressed

    private void tblLista5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblLista5KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLista5KeyReleased

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel7MousePressed

    private void cboPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPagoActionPerformed

    private void cboObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboObraActionPerformed

    private void btn_vista9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_vista9MouseClicked

    private void btn_vista10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_vista10MouseClicked
        int option = (int) cboPago.getSelectedIndex();
        switch (option) {
            case 1:
                Persona.setVisible(true);
                Inicio.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_btn_vista10MouseClicked

    // ------------switch between colors for Active/Inactive color
    public void resetLblColor(JLabel lbl) {
        lbl.setBackground(new Color(31, 97, 141));
    }

    public void setLblColor(JLabel lbl) {
        lbl.setBackground(new Color(84, 153, 199));
    }

    //-----------End --------
    //Let's create staff options and Avoid data
    /**
     * @param the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new viewPagoGrafica().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Persona;
    private javax.swing.JLabel btn_vista;
    private javax.swing.JLabel btn_vista10;
    private javax.swing.JLabel btn_vista2;
    private javax.swing.JLabel btn_vista3;
    private javax.swing.JLabel btn_vista4;
    private javax.swing.JLabel btn_vista5;
    private javax.swing.JLabel btn_vista6;
    private javax.swing.JLabel btn_vista7;
    private javax.swing.JLabel btn_vista8;
    private javax.swing.JLabel btn_vista9;
    private javax.swing.JComboBox<String> cboObra;
    private javax.swing.JComboBox<String> cboPago;
    private javax.swing.JPanel header;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel main;
    private javax.swing.JTable tblLista;
    private javax.swing.JTable tblLista1;
    private javax.swing.JTable tblLista2;
    private javax.swing.JTable tblLista5;
    private javax.swing.JLabel txtNombreObra;
    // End of variables declaration//GEN-END:variables
//   AsistenciaTO asis;
//   AsistenciaBLL asisb = new AsistenciaBLL();
    AsistenciaTO asis;
    AsistenciaBLL asisb = new AsistenciaBLL();
    ObraBLL oob = new ObraBLL();
    ObraEmpleadosBLL obemp = new ObraEmpleadosBLL();
    ObraEmpleado obe;
    EmpleadoBLL oemp = new EmpleadoBLL();

    private void listaObras() {
        DefaultTableModel tabla = (DefaultTableModel) tblLista.getModel();
        tabla.setRowCount(0);
        try {
            List<Obra> lista = oob.ObraListar();
            for (Obra x : oob.ObraListar()) {
                Object[] fila = {x.getCodigo(), x.getNombre()};
                tabla.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void listaEmpleados() {
        int i = this.tblLista.getSelectedRow();
        DefaultTableModel tabla = (DefaultTableModel) tblLista1.getModel();
        tabla.setRowCount(0);
        try {
            List<EmpleadoTO> lista = oemp.EmpleadoListar3(codigo);
            for (EmpleadoTO x : lista) {
                Object[] fila = {x.getIdempleado(), x.getNombre(), x.getApellido(), fecha(), false, false};
                tabla.addRow(fila);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }
     private void listaAsistencia() {
        int i = this.tblLista1.getSelectedRow();
        DefaultTableModel tabla = (DefaultTableModel) tblLista2.getModel();
        tabla.setRowCount(0);
        try {
            String nombre = (String) tblLista1.getValueAt(i, 1);
            String apellido = (String) tblLista1.getValueAt(i, 2);
            List<AsistenciaTO> lista1 =  asisb.AsistenciaListar(idempleado1);
            for (AsistenciaTO x : lista1) {
                Object[] fila = {idempleado1,nombre,apellido,x.getFecha(),x.getHoras()};
                tabla.addRow(fila);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }

    private AsistenciaTO leerDatos() {
        int hora1=0;
        asis = new AsistenciaTO(idempleado1, Integer.toString(hora1), fecha());
        return asis;
    }

    private void procesar(int opcion) {
        String msg = "";
        try {
            switch (opcion) {
                case 1:
                    asisb.AsistenciaAdicionar(leerDatos());
                    msg = "Empleado registrado con exito";

                    break;

            }
            JOptionPane.showMessageDialog(null, msg);
            listaEmpleados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void cargaCombos() {
        try {
            cboObra.removeAllItems();
            for (Obra ob : oob.ObraListar()) {
                cboObra.addItem(ob.getNombre());
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }
}
